language: python

python:
  - "2.7"
  - "3.3"
before_install:
  - sudo apt-get update
install:
  - pip install gitpython
  - sudo apt-get install python3-setuptools
  - sudo easy_install pip
  - sudo pip install gitpython

script:
  - python -m unittest discover --pattern=starter.py

branches:
  only:
    - master
