language: python

python:
  - "2.7"
  - "3.3"
before_install:
  - sudo apt-get update
install:
  - pip install gitpython
  - apt-get install python3-setuptools
  - sudo easy_install3 pip
  - pip3 install gitpython

script:
  - {envpython} -m unittest discover --pattern=starter.py

branches:
  only:
    - master
